site_name: '货物管理业务服务组件'
repo_url: 'http://gitlab.icarcloud.net/iCarCloud/BCS/BCSystem/IntelligentCabinet/GoodsBusiServer'
repo_name: 'GitLab'
site_author : 'lipy'
docs_dir : 'apidoc'
pages:
  - '主页': 'index.md'
#### theme type: readthedocs bootstrap cerulean cosmo cyborg slate united yeti
theme: readthedocs