-- MySQL Script generated by MySQL Workbench
-- Fri Mar 16 16:30:11 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema CabinetServerDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `CabinetServerDB` ;

-- -----------------------------------------------------
-- Schema CabinetServerDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CabinetServerDB` DEFAULT CHARACTER SET utf8 ;
USE `CabinetServerDB` ;

-- -----------------------------------------------------
-- Table `CabinetServerDB`.`Directories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CabinetServerDB`.`Directories` ;

CREATE TABLE IF NOT EXISTS `CabinetServerDB`.`Directories` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '数据项自增ID',
  `uuid` CHAR(30) NOT NULL COMMENT '数据项UUID',
  `name` VARCHAR(100) NULL COMMENT '目录名称',
  `description` VARCHAR(500) NULL COMMENT '描述',
  `status` VARCHAR(45) NULL COMMENT '状态',
  `createdAt` TIMESTAMP NULL COMMENT '创建时间',
  `modifiedAt` TIMESTAMP NULL COMMENT '修改时间',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CabinetServerDB`.`Cabinets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CabinetServerDB`.`Cabinets` ;

CREATE TABLE IF NOT EXISTS `CabinetServerDB`.`Cabinets` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '数据项自增ID',
  `uuid` CHAR(30) NOT NULL COMMENT '数据项UUID',
  `directoryUUID` CHAR(30) NULL COMMENT '所属目录UUID',
  `name` VARCHAR(100) NULL COMMENT '柜子名称',
  `description` VARCHAR(500) NULL COMMENT '描述',
  `address` VARCHAR(500) NULL COMMENT '地址',
  `boxCount` INT NULL COMMENT '盒子总数',
  `number` VARCHAR(45) NULL COMMENT '编号',
  `usedCount` INT NULL COMMENT '已经使用数量',
  `noticerUUID` CHAR(30) NULL,
  `noticerHref` VARCHAR(500) NULL COMMENT '关注者资源链接',
  `status` VARCHAR(45) NULL COMMENT '状态',
  `createdAt` TIMESTAMP NULL COMMENT '创建时间',
  `modifiedAt` TIMESTAMP NULL COMMENT '修改时间',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC),
  INDEX `directoryUUID_idx` (`directoryUUID` ASC),
  INDEX `noticerUUID_idx` (`noticerUUID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CabinetServerDB`.`Boxes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CabinetServerDB`.`Boxes` ;

CREATE TABLE IF NOT EXISTS `CabinetServerDB`.`Boxes` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '数据项自增id',
  `uuid` CHAR(30) NOT NULL COMMENT '数据项UUID',
  `cabinetUUID` CHAR(30) NULL COMMENT '所属柜子UUID',
  `number` VARCHAR(45) NULL COMMENT '盒子编号',
  `length` DOUBLE NULL COMMENT '长',
  `width` DOUBLE NULL COMMENT '宽',
  `height` DOUBLE NULL COMMENT '高',
  `volume` DOUBLE NULL COMMENT '容量',
  `status` VARCHAR(45) NULL COMMENT '状态',
  `createdAt` TIMESTAMP NULL,
  `modifiedAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC),
  INDEX `cabinetUUID_idx` (`cabinetUUID` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
